version: '3'
services: 
  app:
    container_name: node-practice
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - '3050:3050'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo 
    ports: 
      - '27017:27017'
  mongo_seed: 
    build: './mongo-seed'